name: 'Korbit AI mentor'
description: 'Github action for Korbit AI mentor scan to be triggered'
branding:
  icon: 'zap'
  color: 'gray-dark'
inputs:
  paths:
    description: 'The path to the local file or folder to be scan. List of valid paths separated by space.'
    required: true
    default: "."
  threshold_priority:
    description: 'Issues found must be above this priority score to be presented (on a scale of 0-10).'
    required: false
    default: "0"
  threshold_confidence:
    description: 'Issues found must be above this confidence score to be presented (on a scale of 0-10).'
    required: false
    default: "0"
  headless:
    description: 'Will trigger an exit code if issues have been found.'
    required: false
    default: "true"
  is_scan_pr:
    description: 'Flag to run a scan only on diff files for the current active branch against a `compare_branch`.'
    required: false
    default: "false"
  scan_pr_path:
    description: 'The path to the git repository to be scanned.'
    required: false
    default: "."
  scan_pr_compare_branch:
    description: 'The branch to be compared to, for PR analysis.'
    required: false
    default: "master"
  secret_id:
    description: 'The given secret id generated on mentor.korbit.ai'
    required: true
  secret_key:
    description: 'The given secret key generated on mentor.korbit.ai'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    KORBIT_SECRET_ID: ${{ inputs.secret_id }}
    KORBIT_SECRET_KEY: ${{ inputs.secret_key }}
  args:
    - ${{ inputs.path }}
    - ${{ inputs.threshold_priority }}
    - ${{ inputs.threshold_confidence }}
    - ${{ inputs.headless }}
    - ${{ inputs.is_scan_pr }}
    - ${{ inputs.scan_pr_path }}
    - ${{ inputs.scan_pr_compare_branch }}
