name: Testing current action without version
on: [push]

jobs:
  check_files:
    runs-on: ubuntu-latest
    name: An example of using the Korbit AI mentor github action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check file using local github action
        uses: ./ # Uses an action in the root directory
        with:
          threshold_confidence: 9
          threshold_priority: 9
          is_scan_pr: true
          scan_pr_path: .
          scan_pr_compare_branch: ${{ github.base_ref }}
          headless: true
          secret_id: ${{ secrets.KORBIT_SECRET_ID }}
          secret_key: ${{ secrets.KORBIT_SECRET_KEY }}
